/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ejemplojni_lib_JavaCostos */

#ifndef _Included_ejemplojni_lib_JavaCostos
#define _Included_ejemplojni_lib_JavaCostos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ejemplojni_lib_JavaCostos
 * Method:    calcularValores
 * Signature: (FFII)V
 */
JNIEXPORT void JNICALL Java_ejemplojni_lib_JavaCostos_calcularValores
  (JNIEnv *, jobject, jfloat, jfloat, jint, jint);

/*
 * Class:     ejemplojni_lib_JavaCostos
 * Method:    generarEstadoResultados
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_ejemplojni_lib_JavaCostos_generarEstadoResultados
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
