/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCostos */

#ifndef _Included_JavaCostos
#define _Included_JavaCostos
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCostos
 * Method:    calcularValores
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_JavaCostos_calcularValores
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
